services:
  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db_data: